name: Build for Linux
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential libsdl2-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools liblua5.1-dev libx264-dev libx265-dev ffmpeg libarchive-dev libminizip-dev libminizip1 minizip zlib1g-dev mesa-utils pkgconf
          #wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6/+archive/ics-plus-aosp/sysroot/usr/include/sys.tar.gz
          #mkdir -p /usr/include/sys
          #sudo tar xf x86_64-linux-glibc2.7-4.6-ics-plus-aosp-sysroot-usr-include-sys.tar.gz -C /usr/include/sys
          #wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6/+archive/ics-plus-aosp/sysroot/usr/include/bits.tar.gz
          #mkdir -p /usr/include/bits
          #sudo tar xf bits.tar.gz /usr/include/bits

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..# -DQt5_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5 -DQt5Widgets_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets -DQt5OpenGL_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL -DQt5Gui_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui -DQt5Core_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5Core -DZLIB_LIBRARY=/usr/lib/x86_64-linux-gnu/libz.so -DZLIB_INCLUDE_DIR=/usr/include ..
          make -j$(nproc)
          cd ..

      - name: Create package directory
        run: |
          mkdir -p fceux-2.6.6-amd64/DEBIAN
          mkdir fceux-2.6.6-amd64/usr
          echo "Package: FCEUX\
          Version: 2.6.6\
          Architecture: amd64\
          Maintainer: Finn Baltazar\
          Description: An NES Emulator\
          " > fceux-2.6.6-amd64/DEBIAN/control

      - name: Install FCEUX to DEB package directory
        run: |
          cd build
          make install prefix=../fceux-2.6.6-amd64/usr
          cd ..
          dpkg-deb --build --nocheck fceux-2.6.6-amd64

      - name: Release
        run: |
          gh release create v2.6.6 fceux-2.6.6-amd64.deb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash  
